#!/usr/bin/env bash
# build-openclaw.sh — Generate OpenClaw extension artifacts from Claude Octopus skills
#
# This script reads .claude/skills/*.md, .claude/skills/*/SKILL.md,
# and .claude/commands/*.md,
# extracts YAML frontmatter, and generates OpenClaw-compatible tool
# registrations. It ensures the OpenClaw layer stays in sync with
# the Claude Code plugin (source of truth).
#
# Usage:
#   ./scripts/build-openclaw.sh [--check]
#
# Options:
#   --check   Dry-run mode — exits non-zero if generated files would change
#             (useful in CI to detect drift)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SKILLS_DIR="$PLUGIN_ROOT/.claude/skills"
COMMANDS_DIR="$PLUGIN_ROOT/.claude/commands"
OUTPUT_DIR="$PLUGIN_ROOT/openclaw/src/tools"
CHECK_MODE=false

if [[ "${1:-}" == "--check" ]]; then
    CHECK_MODE=true
fi

list_skill_sources() {
    local dir="$1"

    find "$dir" -maxdepth 1 -type f -name '*.md' -print 2>/dev/null
    find "$dir" -mindepth 2 -maxdepth 2 -type f -name 'SKILL.md' -print 2>/dev/null
}

source_basename() {
    local file="$1"
    local root="$2"
    local basename

    basename=$(basename "$file")
    if [[ "$basename" == "SKILL.md" ]]; then
        basename="$(basename "$(dirname "$file")")/SKILL"
    else
        basename="${basename%.md}"
    fi

    printf '%s\n' "$basename"
}

# --- Extract skill metadata from YAML frontmatter ---
extract_skills() {
    local dir="$1"
    local type="$2"  # "skill" or "command"
    local sources

    if [[ "$type" == "skill" ]]; then
        sources=$(list_skill_sources "$dir" | LC_ALL=C sort)
    else
        sources=$(find "$dir" -maxdepth 1 -type f -name '*.md' -print 2>/dev/null | LC_ALL=C sort)
    fi

    while IFS= read -r file; do
        [[ -f "$file" ]] || continue

        local basename
        basename=$(source_basename "$file" "$dir")

        # Extract frontmatter
        local in_frontmatter=false
        local name=""
        local description=""

        while IFS= read -r line; do
            if [[ "$line" == "---" ]]; then
                if $in_frontmatter; then
                    break
                else
                    in_frontmatter=true
                    continue
                fi
            fi

            if $in_frontmatter; then
                case "$line" in
                    name:*)
                        name=$(echo "$line" | sed 's/^name:[[:space:]]*//' | sed "s/^['\"]//;s/['\"]$//")
                        ;;
                    description:*)
                        description=$(echo "$line" | sed 's/^description:[[:space:]]*//' | sed "s/^['\"]//;s/['\"]$//")
                        ;;
                esac
            fi
        done < "$file"

        [[ -z "$name" ]] && name="$basename"
        [[ -z "$description" ]] && description="No description"

        echo "${type}|${name}|${description}|${basename}"
    done <<< "$sources"
}

# --- Generate tool registry ---
generate_registry() {
    mkdir -p "$OUTPUT_DIR"

    local registry_file="$OUTPUT_DIR/index.ts"
    local tmp_file
    tmp_file=$(mktemp)

    cat > "$tmp_file" << 'HEADER'
/**
 * Auto-generated OpenClaw tool registry
 *
 * Generated by: scripts/build-openclaw.sh
 * Source of truth: Claude skill markdown files and command markdown files.
 *
 * DO NOT EDIT MANUALLY — regenerate with: ./scripts/build-openclaw.sh
 */

export interface SkillRegistryEntry {
  name: string;
  description: string;
  type: "skill" | "command";
  file: string;
}

export const SKILL_REGISTRY: SkillRegistryEntry[] = [
HEADER

    local count=0

    # Process skills (sorted for deterministic output across platforms)
    while IFS='|' read -r type name description file; do
        [[ -z "$name" ]] && continue
        # Escape quotes in description
        description=$(echo "$description" | sed 's/"/\\"/g')
        echo "  { name: \"${name}\", description: \"${description}\", type: \"${type}\", file: \"${file}.md\" }," >> "$tmp_file"
        count=$((count + 1))
    done < <(extract_skills "$SKILLS_DIR" "skill" | LC_ALL=C sort)

    # Process commands (sorted for deterministic output across platforms)
    while IFS='|' read -r type name description file; do
        [[ -z "$name" ]] && continue
        description=$(echo "$description" | sed 's/"/\\"/g')
        echo "  { name: \"${name}\", description: \"${description}\", type: \"${type}\", file: \"${file}.md\" }," >> "$tmp_file"
        count=$((count + 1))
    done < <(extract_skills "$COMMANDS_DIR" "command" | LC_ALL=C sort)

    echo "];" >> "$tmp_file"
    echo "" >> "$tmp_file"
    echo "export const REGISTRY_COUNT = ${count};" >> "$tmp_file"

    if $CHECK_MODE; then
        if [[ -f "$registry_file" ]] && diff -q "$tmp_file" "$registry_file" > /dev/null 2>&1; then
            echo "OpenClaw registry is up to date (${count} entries)."
            rm "$tmp_file"
            return 0
        else
            echo "ERROR: OpenClaw registry is out of date. Run: ./scripts/build-openclaw.sh" >&2
            if [[ -f "$registry_file" ]]; then
                echo "Diff:" >&2
                diff -u "$registry_file" "$tmp_file" >&2 || true
            fi
            rm "$tmp_file"
            return 1
        fi
    fi

    mv "$tmp_file" "$registry_file"
    echo "Generated OpenClaw registry: ${count} entries → ${registry_file}"
}

# --- Main ---
echo "Building OpenClaw compatibility layer..."
echo "Plugin root: $PLUGIN_ROOT"
echo ""

generate_registry

echo ""
echo "Build complete."
